-- 산업안전기사 bulk seed is TOO LARGE for Supabase SQL Editor.
--
-- Do one of:
--   A) pnpm seed:isan   (recommended — uses service_role)
--   B) Run files in supabase/seed-chunks/ one by one (00 → 14)
--
-- See docs/SUPABASE_SETUP.md
--
-- This migration is intentionally empty so `db push` / SQL Editor
-- do not choke on a 2.5MB file.
SELECT 1;
